pinpoint-gamble/config/routes.rb
PinpointGamble::Application.routes.draw do
  devise_for :players, :controllers => { :sessions => "player_sessions" }
  
  devise_scope :player do
  	get "logout" => "player_sessions#destroy"
  	get "login"  => "player_sessions#create"
  end
  
  namespace :api do
  	namespace :v1 do
   	    get "/session" => "players#session", as: "token"
   	    
    	resources :devices
	    resources :broadcasts
	    resources :games
   	    resources :players
    end
  end

  root :to => 'games#index'

end

pinpoint-gamble/app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :player
  
  attr_accessible :os, :resolution, :type, :uuid
end

pinpoint-gamble/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end
end

pinpoint-gamble/app/helpers/devices_helper.rb
module DevicesHelper
end

pinpoint-gamble/app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br />
    <%= f.text_field :uuid %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :os %><br />
    <%= f.text_field :os %>
  </div>
  <div class="field">
    <%= f.label :resolution %><br />
    <%= f.text_field :resolution %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pinpoint-gamble/app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

pinpoint-gamble/app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <tr>
    <th>Uuid</th>
    <th>Type</th>
    <th>Os</th>
    <th>Resolution</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td><%= device.uuid %></td>
    <td><%= device.type %></td>
    <td><%= device.os %></td>
    <td><%= device.resolution %></td>
    <td><%= link_to 'Show', device %></td>
    <td><%= link_to 'Edit', edit_device_path(device) %></td>
    <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_device_path %>

pinpoint-gamble/app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

pinpoint-gamble/app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uuid:</b>
  <%= @device.uuid %>
</p>

<p>
  <b>Type:</b>
  <%= @device.type %>
</p>

<p>
  <b>Os:</b>
  <%= @device.os %>
</p>

<p>
  <b>Resolution:</b>
  <%= @device.resolution %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>