pinpoint-gamble/config/routes.rb
PinpointGamble::Application.routes.draw do
  devise_for :players, :controllers => { :sessions => "player_sessions" }
  
  devise_scope :player do
  	get "logout" => "player_sessions#destroy"
  	get "login"  => "player_sessions#create"
  end
  
  namespace :api do
  	namespace :v1 do
   	    get "/session" => "players#session", as: "token"
   	    
    	resources :devices
	    resources :broadcasts
	    resources :games
   	    resources :players
    end
  end

  root :to => 'games#index'

end

pinpoint-gamble/app/models/player.rb
class Player < ActiveRecord::Base
  has_many :games, :through => :broadcasts
  has_many :devices
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :username, :password_confirmation, :remember_me, :token_authenticatable, :guest
  # attr_accessible :title, :body
end

pinpoint-gamble/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  respond_to :json
  
  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
  
  def session
  	respond_with( { session: request.session_options[:id] } )
  end
end

pinpoint-gamble/app/helpers/players_helper.rb
module PlayersHelper
end

pinpoint-gamble/app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pinpoint-gamble/app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

pinpoint-gamble/app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

pinpoint-gamble/app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

pinpoint-gamble/app/views/players/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>