pinpoint-gamble/config/routes.rb
PinpointGamble::Application.routes.draw do
  devise_for :players, :controllers => { :sessions => "player_sessions" }
  
  devise_scope :player do
  	get "logout" => "player_sessions#destroy"
  	get "login"  => "player_sessions#create"
  end
  
  namespace :api do
  	namespace :v1 do
   	    get "/session" => "players#session", as: "token"
   	    
    	resources :devices
	    resources :broadcasts
	    resources :games
   	    resources :players
    end
  end

  root :to => 'games#index'

end

pinpoint-gamble/app/models/broadcast.rb
class Broadcast < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
  
  attr_accessible :inside, :lat, :lng, :x, :y
end

pinpoint-gamble/app/controllers/broadcasts_controller.rb
class BroadcastsController < ApplicationController
  # GET /broadcasts
  # GET /broadcasts.json
  def index
    @broadcasts = Broadcast.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @broadcasts }
    end
  end

  # GET /broadcasts/1
  # GET /broadcasts/1.json
  def show
    @broadcast = Broadcast.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @broadcast }
    end
  end

  # GET /broadcasts/new
  # GET /broadcasts/new.json
  def new
    @broadcast = Broadcast.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @broadcast }
    end
  end

  # GET /broadcasts/1/edit
  def edit
    @broadcast = Broadcast.find(params[:id])
  end

  # POST /broadcasts
  # POST /broadcasts.json
  def create
    @broadcast = Broadcast.new(params[:broadcast])

    respond_to do |format|
      if @broadcast.save
        format.html { redirect_to @broadcast, notice: 'Broadcast was successfully created.' }
        format.json { render json: @broadcast, status: :created, location: @broadcast }
      else
        format.html { render action: "new" }
        format.json { render json: @broadcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /broadcasts/1
  # PUT /broadcasts/1.json
  def update
    @broadcast = Broadcast.find(params[:id])

    respond_to do |format|
      if @broadcast.update_attributes(params[:broadcast])
        format.html { redirect_to @broadcast, notice: 'Broadcast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @broadcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /broadcasts/1
  # DELETE /broadcasts/1.json
  def destroy
    @broadcast = Broadcast.find(params[:id])
    @broadcast.destroy

    respond_to do |format|
      format.html { redirect_to broadcasts_url }
      format.json { head :no_content }
    end
  end
end

pinpoint-gamble/app/helpers/broadcasts_helper.rb
module BroadcastsHelper
end

pinpoint-gamble/app/views/broadcasts/_form.html.erb
<%= form_for(@broadcast) do |f| %>
  <% if @broadcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@broadcast.errors.count, "error") %> prohibited this broadcast from being saved:</h2>

      <ul>
      <% @broadcast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br />
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.text_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.text_field :y %>
  </div>
  <div class="field">
    <%= f.label :inside %><br />
    <%= f.check_box :inside %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pinpoint-gamble/app/views/broadcasts/edit.html.erb
<h1>Editing broadcast</h1>

<%= render 'form' %>

<%= link_to 'Show', @broadcast %> |
<%= link_to 'Back', broadcasts_path %>

pinpoint-gamble/app/views/broadcasts/index.html.erb
<h1>Listing broadcasts</h1>

<table>
  <tr>
    <th>Lat</th>
    <th>Lng</th>
    <th>X</th>
    <th>Y</th>
    <th>Inside</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @broadcasts.each do |broadcast| %>
  <tr>
    <td><%= broadcast.lat %></td>
    <td><%= broadcast.lng %></td>
    <td><%= broadcast.x %></td>
    <td><%= broadcast.y %></td>
    <td><%= broadcast.inside %></td>
    <td><%= link_to 'Show', broadcast %></td>
    <td><%= link_to 'Edit', edit_broadcast_path(broadcast) %></td>
    <td><%= link_to 'Destroy', broadcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Broadcast', new_broadcast_path %>

pinpoint-gamble/app/views/broadcasts/new.html.erb
<h1>New broadcast</h1>

<%= render 'form' %>

<%= link_to 'Back', broadcasts_path %>

pinpoint-gamble/app/views/broadcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lat:</b>
  <%= @broadcast.lat %>
</p>

<p>
  <b>Lng:</b>
  <%= @broadcast.lng %>
</p>

<p>
  <b>X:</b>
  <%= @broadcast.x %>
</p>

<p>
  <b>Y:</b>
  <%= @broadcast.y %>
</p>

<p>
  <b>Inside:</b>
  <%= @broadcast.inside %>
</p>


<%= link_to 'Edit', edit_broadcast_path(@broadcast) %> |
<%= link_to 'Back', broadcasts_path %>